language: python
php:
    - 7.0
sudo: false
before_install:
    - 'wget http://hiqdev.com/hidev/hidev.phar -O hidev.phar && chmod a+x hidev.phar'
    - './hidev.phar --version'
    - './hidev.phar travis/before_install'
install:
    - './hidev.phar travis/install'
script:
    - './hidev.phar travis/script'
